### ISSUE TITLE
Auth guard [guardian] is not defined.

### ISSUE THREAD

**Issue by ScSherifTarek** [rinvex/cortex-auth#81]
![image](https://user-images.githubusercontent.com/44446211/63230234-2653d300-c20a-11e9-92f1-886825aa0e30.png)

When I try to access the admin area I get this error, I solved it temporarily be removing the adminarea from guardians in the config file

But after that, I get `These credentails do not match our records`  error 

![image](https://user-images.githubusercontent.com/44446211/63230237-39ff3980-c20a-11e9-8c64-9bd28f3c101b.png)

After some debuging, I found that the error comes from getting the guard/access area a small `"s"` character added in guessGuard solved the `credentials` error but the `Auth guard [guardian] is not defined.` error still there, I think it has side effects but it worked for me for now

![image](https://user-images.githubusercontent.com/44446211/63230307-2ef8d900-c20b-11e9-8f2c-a9e91e82eef3.png)

**Comment by ScSherifTarek** [comment]
After more debugging and searching, I found where the problem starts, the problem starts with this [commit](https://github.com/rinvex/cortex-foundation/commit/b7fbac08a4c69dbd815655df0d20d6ebfddccb40) when I reverse it all things get well

**Comment by Omranic** [comment]
Are you still having the same issue with the latest released versions?
I assume this has been fixed recently, so would you check and confirm..

**Comment by ScSherifTarek** [comment]
Cool! it's solved.
