### ISSUE TITLE
Update admin doesn't work

### ISSUE THREAD

**Issue by mohamed-hendawy** [rinvex/cortex-auth#97]
When you try to update admin details `$request->validated()` return empty array because [AdminFormRequest](https://github.com/rinvex/cortex-auth/blob/master/src/Http/Requests/Adminarea/AdminFormRequest.php#L97) return empty rules array in cause update

**Comment by Omranic** [comment]
Thank you, issue confirmed.

Reviewed and update is needed, please use the following syntax instead @hendawy
`in_array($this->getRealMethod(), ['PUT', 'POST', 'PATCH'])`

Also this issue exists here `app/cortex/auth/src/Http/Requests/Managerarea/ManagerFormRequest.php:97`

**Comment by Omranic** [comment]
Fixed in rinvex#97
